### ISSUE TITLE
Remove `app` arg from `Block` constructor

### ISSUE THREAD

**Issue by caub** [wurdcms/wurd-node-v3#5]
I think `Block` doesn't need to know about `app` https://github.com/wurdcms/wurd-node/blob/master/src/block.js#L9

@powmedia

**Comment by powmedia** [comment]
No it's not strictly required for the functionality but I believe it's there so that the app name can be accessed easily from within any block and so that a block has a similar api to the main `wurd` module; sometimes this is used for when loading the editor widget from a template
